# Generated by Django 5.2.5 on 2025-08-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"verbose_name": "Кошелёк", "verbose_name_plural": "Кошельки"},
        ),
        migrations.AlterModelOptions(
            name="walletoperations",
            options={"verbose_name": "Операция", "verbose_name_plural": "Операции"},
        ),
    ]
