# Generated by Django 5.2.5 on 2025-08-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_wallet_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="walletoperations",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
            },
        ),
    ]
