# Generated by Django 5.2.5 on 2025-08-09 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_alter_walletoperations_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["id"],
                "verbose_name": "Кошелёк",
                "verbose_name_plural": "Кошельки",
            },
        ),
    ]
